name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        cd cli
        pub get
    - name: runtests
      run: |
        cd cli
        pub run test
